users:
  - name: renovate
    tokenSecretRef: renovate-secret # ???
organizations:
  - name: ops
    description: Operations
    teams:
      - name: Owners
        members:
          - renovate
repositories:
  - name: homelab
    owner: ops
    private: false
    migrate:
      source: https://github.com/khuedoan/homelab
      mirror: false
    webhooks:
      - http://gitea-webhook.tekton-pipelines:3000
  - name: blog
    owner: khuedoan
    migrate:
      source: https://github.com/khuedoan/blog
      mirror: true
    webhooks:
      - http://gitea-webhook.tekton-pipelines:3000
  - name: backstage
    owner: khuedoan
    migrate:
      source: https://github.com/khuedoan/backstage
      mirror: true
    webhooks:
      - http://gitea-webhook.tekton-pipelines:3000
