metal:
  children:
    masters:
      hosts:
        metal0: {ansible_host: 192.168.50.200, mac: 'e4:5f:01:0e:7f:b1', disk: mmcblk0, network_interface: eth0, serial_ends: '4a48539d'}
        metal1: {ansible_host: 192.168.50.201, mac: 'e4:5f:01:1a:a7:f7', disk: mmcblk0, network_interface: eth0, serial_ends: 'a3d3e594'}
        metal2: {ansible_host: 192.168.50.202, mac: 'e4:5f:01:0e:98:f0', disk: mmcblk0, network_interface: eth0, serial_ends: 'aa7448b9'}
    workers:
      hosts:
        metal3: {ansible_host: 192.168.50.203, mac: 'e4:5f:01:54:0c:cf', disk: mmcblk0, network_interface: eth0, serial_ends: '942bce34'}
