metal:
  children:
    masters:
      hosts:
        metal0: {ansible_host: 192.168.50.200, mac: 'e4:5f:01:0e:7f:b1', disk: sda, network_interface: eno1}
        metal1: {ansible_host: 192.168.50.201, mac: 'e4:5f:01:1a:a7:f7', disk: sda, network_interface: eno1}
        metal2: {ansible_host: 192.168.50.202, mac: 'e4:5f:01:0e:98:f0', disk: sda, network_interface: eno1}
    workers:
      hosts:
        metal3: {ansible_host: 192.168.50.203, mac: 'e4:5f:01:54:0c:cf', disk: sda, network_interface: eno1}

