apiVersion: external-secrets.io/v1alpha1
kind: ExternalSecret
metadata:
  name: {{ .Values.gitea.gitea.admin.existingSecret }}
  namespace: {{ .Release.Namespace }}
spec:
  secretStoreRef:
    name: vault
    kind: ClusterSecretStore
  target:
    template:
      data:
        username: gitea_admin
  data:
    - secretKey: password
      remoteRef:
        key: /gitea/admin-password
