- path: gitea/admin
  data:
    - key: password
      length: 32
      special: true
- path: gitea/renovate
  data:
    - key: password
      length: 32
      special: true
    - key: token
      length: 40
      special: false
- path: trow/admin
  data:
    - key: password
      length: 32
      special: true
- path: matrix/alert
  data:
    - key: password
      length: 32
      special: true
